import '@radix-ui/themes/styles.css';
import './globals.css';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Container, Theme } from '@radix-ui/themes';
import { ThemeProvider } from 'next-themes';

import { Header } from '@/components/header';
import { NoiseEffect } from '@/components/noise-effect';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Nitin Panwar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NoiseEffect />
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div className="blur" />
          <Theme
            accentColor="gray"
            grayColor="gray"
            hasBackground={false}
            panelBackground="translucent"
            radius="none"
            scaling="100%"
          >
            <Container
              size={{ initial: '1', sm: '2' }}
              py={{ sm: '4', md: '6' }}
              px={{ initial: '6' }}
            >
              <Header />
              {children}
            </Container>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
